services:
  winter-backend-cardano:
    build: .
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

  db:
    image: postgres:17.4
    ports:
      - '${POSTGRES_HOST_PORT:-5432}:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: 'json-file'
      options:
        max-size: '100M'

volumes:
  postgres-data:
